/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inventory.ui;

import com.inventory.dao.UserDAO;
import com.inventory.dto.UserDTO;
import java.io.File;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Users extends javax.swing.JPanel {

    File f;
    JFileChooser chooser;

    /**
     * Creates new form NewJPanel
     */
    public Users() {

        initComponents();

        //usernameTxt.setEnabled(false);
        chooser = new JFileChooser();
        editBttn.setEnabled(false);
        UserdeleteBttn.setEnabled(false);
        btnEditDetails.setEnabled(false);
        loadDatas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addBttn = new javax.swing.JLabel();
        locationLab = new javax.swing.JLabel();
        userComboBox = new javax.swing.JComboBox();
        fullNameLab = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        locationTxt = new javax.swing.JTextField();
        fullNameTxt = new javax.swing.JTextField();
        phoneLab = new javax.swing.JLabel();
        UserdeleteBttn = new javax.swing.JLabel();
        clearBttn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editBttn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fullNameLab1 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fullNameLab2 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        passwordTxt2 = new javax.swing.JTextField();
        fullNameLab3 = new javax.swing.JLabel();
        fullNameLab4 = new javax.swing.JLabel();
        btnEditDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPanelMouseClicked(evt);
            }
        });
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 1080, 10));

        jLabel2.setFont(new java.awt.Font("Comfortaa", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("USERS");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PLEASE FILL ALL THE FIELDS"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/ui/images/addPeople.png"))); // NOI18N
        addBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBttnMouseClicked(evt);
            }
        });
        jPanel1.add(addBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 374, -1, -1));

        locationLab.setText("Location:");
        jPanel1.add(locationLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 165, -1, -1));

        userComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMINISTRATOR", "NORMAL USER" }));
        userComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(userComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 225, 40));

        fullNameLab.setText("Full Name: ");
        jPanel1.add(fullNameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 127, -1, -1));

        phoneTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 206, 225, 27));

        locationTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(locationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 159, 225, 27));

        fullNameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(fullNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 121, 225, 27));

        phoneLab.setText("Phone:");
        jPanel1.add(phoneLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 212, -1, -1));

        UserdeleteBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/ui/images/deletelarge.png"))); // NOI18N
        UserdeleteBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserdeleteBttnMouseClicked(evt);
            }
        });
        jPanel1.add(UserdeleteBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 374, -1, -1));

        clearBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/ui/images/clear.png"))); // NOI18N
        clearBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBttnMouseClicked(evt);
            }
        });
        jPanel1.add(clearBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 374, -1, -1));

        jLabel3.setText("Add");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 428, -1, -1));

        jLabel5.setText("Delete");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 428, -1, -1));

        jLabel6.setText("Cancel");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 428, 38, -1));

        editBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/ui/images/editPeople.png"))); // NOI18N
        editBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBttnMouseClicked(evt);
            }
        });
        jPanel1.add(editBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 374, -1, -1));

        jLabel4.setText("Update");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 428, -1, -1));

        fullNameLab1.setText("Username:");
        jPanel1.add(fullNameLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 249, -1, -1));

        usernameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 244, 225, 25));

        jLabel1.setText("User Type:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 42, -1, -1));

        fullNameLab2.setText("Password:");
        jPanel1.add(fullNameLab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 292, -1, -1));

        passwordTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 287, 225, 25));

        passwordTxt2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(passwordTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 323, 225, 25));

        fullNameLab3.setText("Password:");
        jPanel1.add(fullNameLab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 347, -1, 9));

        fullNameLab4.setText("Confirm");
        jPanel1.add(fullNameLab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 327, -1, -1));

        btnEditDetails.setText("Edit Details");
        btnEditDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 80, 328, 460));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 742, 458));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userComboBoxActionPerformed

    public String encryptPassword(String input) {
        String encPass = null;
        if (input == null) {
            return null;
        }

        try {
            MessageDigest digest = MessageDigest.getInstance("MD5");
            digest.update(input.getBytes(), 0, input.length());
            encPass = new BigInteger(1, digest.digest()).toString(16);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return encPass;
    }

    String user;
    private void addBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBttnMouseClicked
        UserDTO userdto = new UserDTO();

        if (fullNameTxt.getText().equals("") || locationTxt.getText().equals("") || phoneTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields!");
        } else {

            if (passwordTxt.getText().equals(passwordTxt2.getText())) {
                user = (String) userComboBox.getSelectedItem();
                userdto.setFullName(fullNameTxt.getText());
                userdto.setLocation(locationTxt.getText());
                userdto.setPhone(phoneTxt.getText());
                userdto.setCategory(user);
                userdto.setUsername(usernameTxt.getText());
                userdto.setPassword(passwordTxt.getText());
                new UserDAO().addUserDAO(userdto, user);

                fullNameTxt.setText("");
                locationTxt.setText("");
                phoneTxt.setText("");
                usernameTxt.setText("");
                passwordTxt.setText("");

                editBttn.setEnabled(false);
                UserdeleteBttn.setEnabled(false);
                btnEditDetails.setEnabled(false);

                loadDatas();
            } else {
                JOptionPane.showMessageDialog(null, "passwords do not match!");
            }
        }
    }//GEN-LAST:event_addBttnMouseClicked
    String username;
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.getSelectedRow();
        int column = table.getColumnCount();
        Object[] val = new Object[column];
        for (int i = 0; i < column; i++) {
            val[i] = table.getValueAt(row, i);
        }
        usernameTxt.setText(val[3].toString());
        fullNameTxt.setText((String) val[0]);
        locationTxt.setText((String) val[1]);
        phoneTxt.setText((String) val[2]);
        user = (String) userComboBox.getSelectedItem();
        userComboBox.setSelectedItem(user);
        username = (String) val[3];

        fullNameTxt.setEditable(false);
        locationTxt.setEditable(false);
        phoneTxt.setEditable(false);
        usernameTxt.setEditable(false);
        passwordTxt.setEditable(false);
        passwordTxt2.setEditable(false);

        editBttn.setEnabled(true);
        UserdeleteBttn.setEnabled(true);
        btnEditDetails.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void UserdeleteBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserdeleteBttnMouseClicked
        if (table.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Select a table data first!");
        } else {
            new UserDAO().deleteUserDAO(String.valueOf(table.getValueAt(table.getSelectedRow(), 3)));

            fullNameTxt.setText("");
            locationTxt.setText("");
            phoneTxt.setText("");
            usernameTxt.setText("");
            passwordTxt.setText("");

            editBttn.setEnabled(false);
            UserdeleteBttn.setEnabled(false);
            btnEditDetails.setEnabled(false);
            loadDatas();
        }
    }//GEN-LAST:event_UserdeleteBttnMouseClicked

    private void clearBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBttnMouseClicked
        usernameTxt.setText("");
        fullNameTxt.setText("");
        locationTxt.setText("");
        phoneTxt.setText("");
        passwordTxt.setText("");

        fullNameTxt.setEditable(true);
        locationTxt.setEditable(true);
        phoneTxt.setEditable(true);
        usernameTxt.setEditable(true);
        passwordTxt.setEditable(true);
        passwordTxt2.setEditable(true);

        editBttn.setEnabled(false);
        UserdeleteBttn.setEnabled(false);
        btnEditDetails.setEnabled(false);
    }//GEN-LAST:event_clearBttnMouseClicked
    String filename;
    private void mainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseClicked
        usernameTxt.setText("");
        fullNameTxt.setText("");
        locationTxt.setText("");
        phoneTxt.setText("");
        passwordTxt.setText("");
    }//GEN-LAST:event_mainPanelMouseClicked

    private void editBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBttnMouseClicked
        if (table.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Select a table data first!");
        } else {
            UserDTO userdto = new UserDTO();

            if (fullNameTxt.getText().equals("") || locationTxt.getText().equals("") || phoneTxt.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill all the fields!");
            } else {
                user = (String) userComboBox.getSelectedItem();
                userdto.setFullName(fullNameTxt.getText());
                userdto.setLocation(locationTxt.getText());
                userdto.setPhone(phoneTxt.getText());
                userdto.setUsername(usernameTxt.getText());
                userdto.setCategory(user);
                new UserDAO().editUserDAO(userdto);

                fullNameTxt.setText("");
                locationTxt.setText("");
                phoneTxt.setText("");
                usernameTxt.setText("");
                passwordTxt.setText("");

                editBttn.setEnabled(false);
                UserdeleteBttn.setEnabled(false);
                btnEditDetails.setEnabled(false);
                loadDatas();
            }
        }
    }//GEN-LAST:event_editBttnMouseClicked

    private void btnEditDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDetailsActionPerformed
        fullNameTxt.setEditable(true);
        locationTxt.setEditable(true);
        phoneTxt.setEditable(true);
        //usernameTxt.setEditable(true);
        //passwordTxt.setEditable(true);
        //passwordTxt2.setEditable(true);
    }//GEN-LAST:event_btnEditDetailsActionPerformed

    public void loadDatas() {
        try {
            UserDAO userDAO = new UserDAO();
            table.setModel(userDAO.buildTableModel(userDAO.getQueryResult1()));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserdeleteBttn;
    private javax.swing.JLabel addBttn;
    private javax.swing.JButton btnEditDetails;
    private javax.swing.JLabel clearBttn;
    private javax.swing.JLabel editBttn;
    private javax.swing.JLabel fullNameLab;
    private javax.swing.JLabel fullNameLab1;
    private javax.swing.JLabel fullNameLab2;
    private javax.swing.JLabel fullNameLab3;
    private javax.swing.JLabel fullNameLab4;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel locationLab;
    private javax.swing.JTextField locationTxt;
    public javax.swing.JPanel mainPanel;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField passwordTxt2;
    private javax.swing.JLabel phoneLab;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTable table;
    private javax.swing.JComboBox userComboBox;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
